### ISSUE TITLE
Provide Non Blocking Iterator Access

### ISSUE THREAD

**Issue by atomfrede** [meplato/mall-java-client#5]
DISCLAIMER: This is just a tracking issues for us (and to get your opinion), we will implement.

We are currently trying to import items into our database and just noticed, that it woul be cool to have more or less direct access to the underlying iterator instead of using a blocking listener as exception handling for a single item becomes a real pain in that case.

So instead of abstracting away the streaming nature of grpc let the client handle it such that iteration can be done by the client.

**Comment by olivere** [comment]
Are you sure this is the right repo? This is for Mall v1, not v2.

**Comment by atomfrede** [comment]
You are totally right :man_facepalming:
